substitutions:
  devicename: "esphome_rgb_led_remote"
  light_entity: "rgb_strip"
  # v- Sets the minimum PWM output the light still works with, so that the light doesnt turn off, when you set it to i.e. 5 %, see "min_power" below
  ZVal: "0.0005"

esphome:
  name: $devicename
  platform: ESP8266
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: $devicename AP
    password: !secret ap_password
    ap_timeout: 1min

captive_portal:

# Define output pins
output:
  - platform: esp8266_pwm
    id: output_red
    pin: GPIO14
    # min_power: Sets the minimum PWM output the light still works with, so that the light doesnt turn off, when you set it to i.e. 5 %
    min_power: $ZVal
    # zero_means_zero: Needed if min_power is used, otherwise the light will remain in minimal state when turned off
    zero_means_zero: true
    inverted: false
  - platform: esp8266_pwm
    id: output_green
    pin: GPIO12
    min_power: $ZVal
    zero_means_zero: true
    inverted: false
  - platform: esp8266_pwm
    id: output_blue
    pin: GPIO4
    min_power: $ZVal
    zero_means_zero: true
    inverted: false

# Define a light entity
light:
  - platform: rgb
    name: $devicename
    id: ${light_entity}
    red: output_red
    green: output_green
    blue: output_blue
    effects:
      - random:
          name: "Smooth"
          transition_length: 30s
          update_interval: 30s
      - random:
          name: "Fade"
          transition_length: 5s
          update_interval: 5s
      - strobe:
          name: "Strobe"
      - strobe:
          name: "Flash"
          colors:
            - state: True
              brightness: 100%
              red: 100%
              blue: 0%
              green: 0%
              duration: 150ms
            - state: False
              duration: 100ms
            - state: True
              brightness: 100%
              red: 0%
              blue: 0%
              green: 100%
              duration: 150ms
            - state: False
              duration: 100ms
            - state: True
              brightness: 100%
              red: 0%
              blue: 100%
              green: 0%
              duration: 150ms
            - state: False
              duration: 100ms
            - state: True
              brightness: 100%
              red: 100%
              blue: 100%
              green: 100%
              duration: 150ms
            - state: False
              duration: 100ms

remote_receiver:
  pin:
    number: 0
    inverted: true
    mode:
      input: true
      pullup: true
  dump: all


# Remote Codes ##############################

# On/Off/Bright ##############################

binary_sensor:
  - platform: remote_receiver
    name: "Remote ON"
    internal: true
    nec:
    # I used the nec format because its just the easiest to edit
      address: 0xEF00
      command: 0xFC03
    on_press:
      then:
        - light.turn_on: ${light_entity}

  - platform: remote_receiver
    name: "Remote OFF"
    internal: true
    nec:
      address: 0xEF00
      command: 0xFD02
    on_press:
      then:
        - light.turn_off: ${light_entity}

  - platform: remote_receiver
    name: "Remote BRIGHTUP"
    internal: true
    nec:
      address: 0xEF00
      command: 0xFF00
    on_press:
      then:
        - light.dim_relative:
            id: ${light_entity}
            relative_brightness: 10%

  - platform: remote_receiver
    name: "Remote BRIGHTDOWN"
    internal: true
    nec:
      address: 0xEF00
      command: 0xFE01
    on_press:
      then:
        - light.dim_relative:
            id: ${light_entity}
            relative_brightness: -10%

# Red ##############################

  - platform: remote_receiver
    name: "Remote RED"
    internal: true
    nec:
      address: 0xEF00
      command: 0xFB04
    on_press:
      then:
        - light.turn_on:
            id: ${light_entity}
            red: 100%
            green: 0%
            blue: 0%
            effect: None

  - platform: remote_receiver
    name: "Remote RED2"
    internal: true
    nec:
      address: 0xEF00
      command: 0xF708
    on_press:
      then:
        - light.turn_on:
            id: ${light_entity}
            red: 100%
            green: 33%
            blue: 0%
            effect: None

  - platform: remote_receiver
    name: "Remote RED3"
    internal: true
    nec:
      address: 0xEF00
      command: 0xF30C
    on_press:
      then:
        - light.turn_on:
            id: ${light_entity}
            red: 100%
            green: 66%
            blue: 0%
            effect: None

  - platform: remote_receiver
    name: "Remote RED4"
    internal: true
    nec:
      address: 0xEF00
      command: 0xEF10
    on_press:
      then:
        - light.turn_on:
            id: ${light_entity}
            red: 66%
            green: 100%
            blue: 0%
            effect: None

  - platform: remote_receiver
    name: "Remote RED5"
    internal: true
    nec:
      address: 0xEF00
      command: 0xEB14
    on_press:
      then:
        - light.turn_on:
            id: ${light_entity}
            red: 33%
            green: 100%
            blue: 0%
            effect: None

# Green ##############################

  - platform: remote_receiver
    name: "Remote GREEN"
    internal: true
    nec:
      address: 0xEF00
      command: 0xFA05
    on_press:
      then:
        - light.turn_on:
            id: ${light_entity}
            red: 0%
            green: 100%
            blue: 0%
            effect: None

  - platform: remote_receiver
    name: "Remote GREEN2"
    internal: true
    nec:
      address: 0xEF00
      command: 0xF609
    on_press:
      then:
        - light.turn_on:
            id: ${light_entity}
            red: 0%
            green: 100%
            blue: 33%
            effect: None

  - platform: remote_receiver
    name: "Remote GREEN3"
    internal: true
    nec:
      address: 0xEF00
      command: 0xF20D
    on_press:
      then:
        - light.turn_on:
            id: ${light_entity}
            red: 0%
            green: 100%
            blue: 66%
            effect: None
                        
  - platform: remote_receiver
    name: "Remote GREEN4"
    internal: true
    nec:
      address: 0xEF00
      command: 0xEE11
    on_press:
      then:
        - light.turn_on:
            id: ${light_entity}
            red: 0%
            green: 66%
            blue: 100%
            effect: None
                        
  - platform: remote_receiver
    name: "Remote GREEN"
    internal: true
    nec:
      address: 0xEF00
      command: 0xEA15
    on_press:
      then:
        - light.turn_on:
            id: ${light_entity}
            red: 0%
            green: 33%
            blue: 100%
            effect: None

# Blue ##############################

  - platform: remote_receiver
    name: "Remote BLUE"
    internal: true
    nec:
      address: 0xEF00
      command: 0xF906
    on_press:
      then:
        - light.turn_on:
            id: ${light_entity}
            red: 0%
            green: 0%
            blue: 100%
            effect: None

  - platform: remote_receiver
    name: "Remote BLUE2"
    internal: true
    nec:
      address: 0xEF00
      command: 0xF50A
    on_press:
      then:
        - light.turn_on:
            id: ${light_entity}
            red: 33%
            green: 0%
            blue: 100%
            effect: None

  - platform: remote_receiver
    name: "Remote BLUE3"
    internal: true
    nec:
      address: 0xEF00
      command: 0xF10E
    on_press:
      then:
        - light.turn_on:
            id: ${light_entity}
            red: 66%
            green: 0%
            blue: 100%
            effect: None

  - platform: remote_receiver
    name: "Remote BLUE4"
    internal: true
    nec:
      address: 0xEF00
      command: 0xED12
    on_press:
      then:
        - light.turn_on:
            id: ${light_entity}
            red: 100%
            green: 0%
            blue: 66%
            effect: None

  - platform: remote_receiver
    name: "Remote BLUE5"
    internal: true
    nec:
      address: 0xEF00
      command: 0xE916
    on_press:
      then:
        - light.turn_on:
            id: ${light_entity}
            red: 100%
            green: 0%
            blue: 33%
            effect: None

# White ##############################

  - platform: remote_receiver
    name: "Remote WHITE"
    internal: true
    nec:
      address: 0xEF00
      command: 0xF807
    on_press:
      then:
        - light.turn_on:
            id: ${light_entity}
            red: 100%
            green: 100%
            blue: 100%
            effect: None

# Effects ##############################

  - platform: remote_receiver
    name: "Remote FLASH"
    internal: true
    nec:
      address: 0xEF00
      command: 0xF40B
    on_press:
      then:
        - light.turn_on:
             id: ${light_entity}
             effect: "Flash"

  - platform: remote_receiver
    name: "Remote STROBE"
    internal: true
    nec:
      address: 0xEF00
      command: 0xF00F
    on_press:
      then:
        - light.turn_on:
             id: ${light_entity}
             effect: "Strobe"

  - platform: remote_receiver
    name: "Remote FADE"
    internal: true
    nec:
      address: 0xEF00
      command: 0xEC13
    on_press:
      then:
        - light.turn_on:
             id: ${light_entity}
             effect: "Fade"

  - platform: remote_receiver
    name: "Remote SMOOTH"
    internal: true
    nec:
      address: 0xEF00
      command: 0xE817
    on_press:
      then:
        - light.turn_on:
             id: ${light_entity}
             effect: "Smooth"

# End ##############################

###Diagnostics - Not shown in HA Dashboard
sensor:
  - platform: uptime
    name: Uptime $devicename
    update_interval: 60s
    entity_category: diagnostic
  - platform: wifi_signal
    name: WiFi $devicename
    update_interval: 60s
    entity_category: diagnostic
button:
  - platform: restart
    name: Restart $devicename
    entity_category: diagnostic
text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP Address $devicename 
      entity_category: diagnostic
    ssid:
      name: Connected SSID $devicename 
      entity_category: diagnostic
    bssid:
      name: Connected BSSID $devicename
      entity_category: diagnostic
    mac_address:
      name: Mac Wifi Address $devicename 
      entity_category: diagnostic
